<?php
/**
 * SearchDesksRequestSortTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Satubaldeeva\DesksClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Desks - OpenAPI 3.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.11
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Satubaldeeva\DesksClient\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * SearchDesksRequestSortTest Class Doc Comment
 *
 * @category    Class
 * @description SearchDesksRequestSort
 * @package     Satubaldeeva\DesksClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class SearchDesksRequestSortTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "SearchDesksRequestSort"
     */
    public function testSearchDesksRequestSort()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "field"
     */
    public function testPropertyField()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
