<?php
/**
 * DesksApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Satubaldeeva\DesksClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Desks - OpenAPI 3.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.11
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Satubaldeeva\DesksClient\Test\Api;

use \Satubaldeeva\DesksClient\Configuration;
use \Satubaldeeva\DesksClient\ApiException;
use \Satubaldeeva\DesksClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DesksApiTest Class Doc Comment
 *
 * @category Class
 * @package  Satubaldeeva\DesksClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DesksApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for addDesks
     *
     * Create a new desk.
     *
     */
    public function testAddDesks()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteDeskById
     *
     * Delete a desks by ID.
     *
     */
    public function testDeleteDeskById()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getDesks
     *
     * Get all existing desks.
     *
     */
    public function testGetDesks()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getDesksById
     *
     * Get a desk by ID.
     *
     */
    public function testGetDesksById()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for replaceDeskById
     *
     * Replace a desk by ID.
     *
     */
    public function testReplaceDeskById()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for searchDesks
     *
     * Search Desks.
     *
     */
    public function testSearchDesks()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateDeskById
     *
     * Update a desk by ID.
     *
     */
    public function testUpdateDeskById()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
