<?php
/**
 * ListsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Satubaldeeva\DesksClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Desks - OpenAPI 3.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.11
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Satubaldeeva\DesksClient\Test\Api;

use \Satubaldeeva\DesksClient\Configuration;
use \Satubaldeeva\DesksClient\ApiException;
use \Satubaldeeva\DesksClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ListsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Satubaldeeva\DesksClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ListsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for addLists
     *
     * Create a new list.
     *
     */
    public function testAddLists()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteListById
     *
     * Delete a list by ID.
     *
     */
    public function testDeleteListById()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getListById
     *
     * Get a list by ID.
     *
     */
    public function testGetListById()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getLists
     *
     * Get all existing lists.
     *
     */
    public function testGetLists()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for replaceListById
     *
     * Replace a list by ID.
     *
     */
    public function testReplaceListById()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateListById
     *
     * Update a list by ID.
     *
     */
    public function testUpdateListById()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
